<?php

namespace BackOfficeBundle\Repository;

/**
 * DeplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeplacementRepository extends \Doctrine\ORM\EntityRepository{

  public function AllDeplacementsRest(){
    return $this->getEntityManager()->createQuery('SELECT i FROM BackOfficeBundle:Deplacement i')->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
  }
/*
  public function OneDeplacementRest(){
    return $this->getEntityManager()->createQuery('SELECT i FROM BackOfficeBundle:Deplacement i')->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
  }
*/
}
