<?php

namespace BackOfficeBundle\Repository;

/**
 * Deplacement_jourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Deplacement_jourRepository extends \Doctrine\ORM\EntityRepository
{
}
