<?php

namespace BackOfficeBundle\Repository;

/**
 * DeplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeplacementRepository extends \Doctrine\ORM\EntityRepository{

  public function findByAllDeplacementsRest(){
    return $this->getEntityManager()->createQuery('SELECT * FROM BackOfficeBundle:Deplacement')->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
  }
  
}
