<?php

namespace BackOfficeBundle\Repository;

/**
 * Type_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_userRepository extends \Doctrine\ORM\EntityRepository
{
}
