<?php

namespace BackOfficeBundle\Repository;

/**
 * Type_deplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_deplacementRepository extends \Doctrine\ORM\EntityRepository
{
}
