<?php

namespace BackOfficeBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllUtilisateurByVille()
    {
        return $this->getEntityManager()->createQuery('Select v.ville ,COUNT(i) nombre_utilisateur FROM BackOfficeBundle:user i INNER JOIN BackOfficeBundle:ville v WITH i.ville = v.id GROUP BY i.ville')->getResult();
    }
    public function findAllUtilisateurAndKilometreBySociete()
      {
          return $this->getEntityManager()->createQuery('Select s.societe,
          (Select COUNT(i2) nombre FROM BackOfficeBundle:user i2 INNER JOIN BackOfficeBundle:societe s2 WITH i2.societe = s2.id GROUP BY i2.societe) AS nombre_utilisateur,
          SUM(dj.nbKm) kilometre
          FROM BackOfficeBundle:user i, BackOfficeBundle:societe s,BackOfficeBundle:DeplacementJour dj, BackOfficeBundle:Deplacement d
          Where i.societe = s.id AND d.user=i.id AND d.id=dj.deplacement
          GROUP BY i.societe')->getResult();
      }
// sql
//SELECT societe,
// (Select COUNT(*) nombre FROM user i INNER JOIN societe s ON i.societe_id = s.id GROUP BY i.societe_id) AS Nombre_utilisateur,
// SUM(dj.nb_km)
// FROM user i, societe s,deplacement_jour dj, deplacement d
// Where i.societe_id = s.id AND d.user_id=i.id AND d.id=dj.deplacement_id
// GROUP BY i.societe_id
}
