<?php

namespace BackOfficeBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllUtilisateurByVille()
    {
      return $this->getEntityManager()->createQuery('Select v.ville ,COUNT(u) nombre_utilisateur FROM BackOfficeBundle:user u INNER JOIN BackOfficeBundle:ville v WITH u.ville = v.id GROUP BY u.ville')->getResult();
    }
  public function findAllUtilisateurAndKilometreBySociete()
    {
      return $this->getEntityManager()->createQuery('Select s.societe,sum(dj.nbKm) nombre_kilometre, COUNT(DISTINCT u.id) nombre_utilisateur
        FROM BackOfficeBundle:DeplacementJour dj, BackOfficeBundle:Deplacement d,BackOfficeBundle:user u,BackOfficeBundle:societe s
        WHERE dj.deplacement=d.id AND d.user=u.id AND s.id=u.societe
        GROUP BY s.id')->getResult();
    }
    //En sql normal :
    // SELECT s.societe,ROUND(sum(dj.nb_km), 2) nombre_kilometre, COUNT(DISTINCT u.id) nombre_utilisateur
    // FROM deplacement_jour dj, deplacement d,user u,societe s
    // WHERE dj.deplacement_id=d.id AND d.user_id=u.id AND s.id=u.societe_id
    // GROUP BY s.id
  public function findKilometreMoisBySocieteAndUtilisateur()
    {
      $annee_en_cour=date("Y",time());
      return $this->getEntityManager()->createQuery('Select s.societe,((sum(dj.nbKm)/COUNT(DISTINCT u.id))/COUNT(DISTINCT d.id)) nombre_kilo_utilisateur , COUNT(DISTINCT u.id) nombre_utilisateur
        FROM BackOfficeBundle:DeplacementJour dj, BackOfficeBundle:Deplacement d,BackOfficeBundle:user u,BackOfficeBundle:societe s
        WHERE dj.deplacement=d.id AND d.user=u.id AND s.id=u.societe AND d.annee='.$annee_en_cour.'
        GROUP BY s.id')->getResult();
    }
    //En sql normal :
    // SELECT s.societe,ROUND(((sum(dj.nb_km)/COUNT(DISTINCT u.id))/COUNT(DISTINCT d.id)), 2) nombre_kilo_utilisateur
    // FROM deplacement_jour dj, deplacement d,user u,societe s
    // WHERE dj.deplacement_id=d.id AND d.user_id=u.id AND s.id=u.societe_id AND d.annee=YEAR(NOW())
    // GROUP BY s.id
}
