webservice:
    resource: "@webserviceBundle/Resources/config/routing.yml"
    prefix:   /api

front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admindep

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
