front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admindep

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
back_office_homepafge:
    path:     /admindep
    defaults: 
     _controller: BackOfficeBundle:Default:index
