service_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Service:index" }
    methods:  GET

service_show:
    path:     /{id}/show
    defaults: { _controller: "BackOfficeBundle:Service:show" }
    methods:  GET

service_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Service:new" }
    methods:  [GET, POST]

service_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:Service:edit" }
    methods:  [GET, POST]

service_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:Service:delete" }
    methods:  DELETE
