back_office_homepage:
    path: /
    defaults: { _controller: BackOfficeBundle:Default:index }
back_office_service:
        resource: "@BackOfficeBundle/Resources/config/routing/service.yml"
        prefix:   /service
back_office_societe:
        resource: "@BackOfficeBundle/Resources/config/routing/societe.yml"
        prefix:   /societe
back_office_deplacementjour:
        resource: "@BackOfficeBundle/Resources/config/routing/deplacementjour.yml"
        prefix:   /deplacementjour
back_office_deplacement:
    resource: "@BackOfficeBundle/Resources/config/routing/deplacement.yml"
    prefix:   /deplacement
back_office_typedeplacement:
    resource: "@BackOfficeBundle/Resources/config/routing/typedeplacement.yml"
    prefix:   /typedeplacement
back_office_ville:
    resource: "@BackOfficeBundle/Resources/config/routing/ville.yml"
    prefix:   /ville
back_office_typeuser:
    resource: "@BackOfficeBundle/Resources/config/routing/typeuser.yml"
    prefix:   /typeuser
back_office_user:
    resource: "@BackOfficeBundle/Resources/config/routing/user.yml"
    prefix:   /user
