BackOfficeBundle\Entity\Deplacement:
    type: entity
    table: null
    repositoryClass: BackOfficeBundle\Repository\DeplacementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        annee:
            type: integer
        mois:
            type: integer
        dateValidation:
            type: date
            column: date_validation
        created:
            type: datetime
        updated:
            type: datetime
        validation:
            type: smallint
    lifecycleCallbacks: {  }
