BackOfficeBundle\Entity\service:
    type: entity
    table: null
    repositoryClass: BackOfficeBundle\Repository\serviceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        service:
            type: string
            length: 255
    lifecycleCallbacks: {  }
