BackOfficeBundle\Entity\Type_deplacement:
    type: entity
    table: null
    repositoryClass: BackOfficeBundle\Repository\Type_deplacementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        typeDeplacement:
            type: string
            length: 255
            column: type_deplacement
        montant:
            type: bigint
        created:
            type: datetime
        updated:
            type: datetime
    lifecycleCallbacks: {  }
