BackOfficeBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: BackOfficeBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        distanceInit:
            type: bigint
            column: distance_init
        created:
            type: datetime
        updated:
            type: datetime
    lifecycleCallbacks: {  }
