BackOfficeBundle\Entity\Ville:
    type: entity
    table: null
    repositoryClass: BackOfficeBundle\Repository\VilleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ville:
            type: string
            length: 255
        cp:
            type: string
            length: 255
    lifecycleCallbacks: {  }
